# cdc-v2.10
method: CaDeX-PF-DFAU
gpu: 0,1
modes: ["train", "val"]
# resume: 223_latest
model:
  model_name: cadex_dfaust

  loss_recon: true
  loss_corr: false

  compress_cdc: true # the cdc is compressed by a sigmoid

  t_perm_inv: true # if true, use PointNet for each frame separately

  homeomorphism_encoder:
    c_dim: 128
    hidden_dim: 128
  canonical_geometry_encoder:
    c_dim: 128
    hidden_dim: 128
  canonical_geometry_decoder:
    c_dim: 128
    hidden_size: 128
  homeomorphism_decoder:
    n_layers: 6
    feature_dims: 128
    hidden_size: [128, 64, 32, 32, 32]
    proj_dims: 128
    code_proj_hidden_size: [128, 128, 128]
    proj_type: simple
    block_normalize: True
    normalization: False

dataset:
  pin_mem: False
  dataset_name: oflow_data
  dataset_proportion: [1.0, 1.0] #  [0.1, 0.1]
  num_workers: 16
  n_query_sample_eval: 10000
  n_training_frames: 5
  oflow_config:
    xyz_range: [-0.5, -0.5, -0.5, 0.5, 0.5, 0.5]
    xyz_padding: 0.1
    voxel_res: 32
    # custom
    training_all_steps: false
    training_multi_files: false # for boosting disk read, only works after downloading our multi-file divided dataset

    # path: resource/data/Humans_multi
    # path: /tmp/leijh/Humans_multi
    path: /home/chang/Videos/DFAUST

    dataset: Humans
    # input_type: dino_seq
    input_type: pcl_seq
    classes: ["data_processed_cadex"]
    train_split: train
    val_split: val
    test_split: test
    dim: 3
    n_training_points: 512
    points_unpackbits: true
    n_training_pcl_points: 100
    input_pointcloud_n: 300
    input_pointcloud_noise: 0.001
    input_pointcloud_corresponding: true
    n_views: 24
    img_size: 224
    img_with_camera: false
    img_augment: false
    length_sequence: 17
    offset_sequence: 15
    n_files_per_sequence: -1
    points_file: points.npz
    mesh_seq_folder: mesh_seq
    points_iou_seq_folder: points_seq
    pointcloud_seq_folder: pcl_seq
    img_seq_folder: color_seq
    generation_interpolate: false

training:
  grad_clip: 4.0
  optim:
    all:
      lr: 0.0001
      decay_schedule: [200, 225, 250]
      decay_factor: [0.3, 0.3, 0.3]
      lr_min: 0.00000001

  total_epoch: 200000
  batch_size: 20
  # initialize_network_file: ["/home/chang/Videos/CaDeX_Voxel_Superres/log/cadex_dfaust_w_pf/checkpoint/207_latest.pt"]
  # initialize_network_name: ["all"]
evaluation:
  eval_every_epoch: 1
  iou_threshold: 0.3
  batch_size: 4
  project_to_final_mesh: false

logging:
  log_dir: cadex_dfaust_w_pf
  loggers: ["mesh", "image", "hist", "video", "xls"]
  viz_training_batch_interval: 99999999999999 # 20
  viz_nontrain_batch_interval: 99999999999999
  viz_epoch_interval: 99999999999999
  checkpoint_epoch: 20 #99
  mesh_viz_interval: 99999999999999

  model_select_metric: iou
  model_select_larger: true

generation:
  occ_if_meshing_cfg:
    batch_pts: 8000
    simplify_nfaces: 5000
